const navbar = [
  {
    id: 1,
    name: "Analitika",
    path: "/analitika",
    isPrivate: true,
    role: ["admin"],
  },
  {
    id: 2,
    name: "Lidlar", // buyurtma
    path: "/lidlar",
    isPrivate: true,
    role: ["admin"],
    children: [
      {
        id: `2-1`,
        name: "Barcha Lidlar",
        path: "/role",
        isPrivate: true,
        role: ["admin", "manager"],
      },
      {
        id: `2-2`,
        name: "Birinchi Dars",
        path: "/hodimlar",
        isPrivate: true,
        role: ["admin", "manager"],
      },
      {
        id: `2-3`,
        name: "Yangi Talabalar",
        path: "/new-students",
        isPrivate: true,
        role: ["admin", "manager"],
      },
    ],
  },
  {
    id: 3,
    name: "Moliya",
    path: "/moliya",
    isPrivate: true,
    role: ["admin"],
  },
  {
    id: 4,
    name: "Talaba",
    path: "/talaba",
    isPrivate: true,
    role: ["admin", "mentor", "manager"],
    children: [
      {
        id: `4-1`,
        name: "Barcha talabalar",
        path: "/all-talabalar",
        isPrivate: true,
        role: ["admin", "manager"],
      },
      {
        id: `4-2`,
        name: "Davomat",
        path: "/davomat",
        isPrivate: true,
        role: ["admin", "manager"],
      },
      {
        id: `4-3`,
        name: "Aktive",
        path: "/active",
        isPrivate: true,
        role: ["admin", "manager"],
      },
      {
        id: `4-4`,
        name: "Arxiv",
        path: "/archive",
        isPrivate: true,
        role: ["admin", "manager"],
      },
      {
        id: `4-5`,
        name: "Ota-onalar",
        path: "/parents",
        isPrivate: true,
        role: ["admin", "manager"],
      },
    ],
  },
  {
    id: 5,
    name: "Guruhlar",
    path: "/guruhlar",
    isPrivate: true,
    role: ["admin", "mentor", "manager"],
    children: [
      {
        id: `5-1`,
        name: "Guruhlar",
        path: "/guruhlar",
        isPrivate: true,
        role: ["admin", "manager"],
      },
      {
        id: `5-2`,
        name: "Dars Jadvali",
        path: "/jadval",
        isPrivate: true,
        role: ["admin", "manager"],
      },
      {
        id: `5-3`,
        name: "Xonalar",
        path: "/xonalar",
        isPrivate: true,
        role: ["admin", "manager"],
      },
    ],
  },
  {
    id: 6,
    name: "Kurslar",
    path: "/kurslar",
    isPrivate: true,
    role: ["admin", "mentor", "manager"],
    children: [
      {
        id: `6-1`,
        name: "Barcha Kurslar",
        path: "/all-kurslar",
        isPrivate: true,
        role: ["admin", "manager"],
      },
      {
        id: `6-2`,
        name: "Yo'nalishlar",
        path: "/yonalish",
        isPrivate: true,
        role: ["admin", "manager"],
      },
    ],
  },
  {
    id: 7,
    name: "HR",
    path: "/hr",
    isPrivate: true,
    role: ["admin", "manager"],
    children: [
      {
        id: `7-1`,
        name: "Ro'llar",
        path: "/role",
        isPrivate: true,
        role: ["admin", "manager"],
      },
      {
        id: `7-2`,
        name: "Hodimlar",
        path: "/hodimlar",
        isPrivate: true,
        role: ["admin", "manager"],
      },
    ],
  },
  {
    id: 8,
    name: "Sozlamalar",
    path: "/sozlamalar",
    isPrivate: true,
    role: ["admin", "manager"],
    children: [
      {
        id: 8 - 1,
        name: "Umumiy Sozlamalar",
        path: "/umumiy",
        isPrivate: true,
        role: ["admin", "manager"],
      },
      {
        id: 8 - 2,
        name: "Manager",
        path: "/manager",
        isPrivate: true,
        role: ["admin", "manager"],
      },
      {
        id: 8 - 3,
        name: "Mentor",
        path: "/mentor",
        isPrivate: true,
        role: ["admin", "manager"],
      },
      {
        id: 8 - 4,
        name: "Talaba",
        path: "/talaba",
        isPrivate: true,
        role: ["admin", "manager"],
      },
    ],
  },
];

export default navbar;
